### ISSUE TITLE
Running test on Android emulator fails

### ISSUE THREAD

**Issue by iksi** [semaphoreci-demos/semaphore-demo-react-native#10]
I’ve been having some issues trying to get the `npm run detox-android-test-release` command to run without errors. Initially I ran into the following error.

```
detox[4635] INFO:  [test.js] configuration="android.emu.release" useCustomLogger=true forceAdbInstall=false DETOX_START_TIMESTAMP=1600872586299 readOnlyEmu=false reportSpecs=true jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e
detox[4647] INFO:  [DetoxServer.js] server listening on localhost:38141...
detox[4647] ERROR: [exec.js/EXEC_FAIL, #1] ""/opt/android-sdk-linux/emulator/emulator" -version" failed with code = 127, stdout and stderr:

detox[4647] ERROR: [exec.js/EXEC_FAIL, #1] 
detox[4647] ERROR: [exec.js/EXEC_FAIL, #1] /opt/android-sdk-linux/emulator/qemu/linux-x86_64/qemu-system-x86_64: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory
```

[Full error log](https://gist.github.com/iksi/a9139fdd1e68a55d3930b8e8c01b40f5)

This error can be resolved by adding the following prologue command to the task:

```
apt-get install pulseaudio
```

After that running `npm run detox-android-test-release` results in the following error that I’ve not been able to solve:

```
detox[5084] INFO:  [test.js] configuration="android.emu.release" useCustomLogger=true forceAdbInstall=false DETOX_START_TIMESTAMP=1600871237068 readOnlyEmu=false reportSpecs=true jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e
detox[5096] INFO:  [DetoxServer.js] server listening on localhost:45275...
detox[5096] ERROR: [EmulatorLauncher.js/SPAWN_FAIL] `/opt/android-sdk-linux/emulator/emulator -verbose -no-audio -no-boot-anim -port 14720 @Pixel_API_28_AOSP` failed with code null
  err: ChildProcessError: `/opt/android-sdk-linux/emulator/emulator -verbose -no-audio -no-boot-anim -port 14720 @Pixel_API_28_AOSP` failed with code null
      at ChildProcess.<anonymous> (/root/redpanda/node_modules/child-process-promise/lib/index.js:132:23)
      at ChildProcess.emit (events.js:198:13)
      at maybeClose (internal/child_process.js:982:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
detox[5096] ERROR: [EmulatorLauncher.js/SPAWN_FAIL] Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
 ((null):0, (null))
```

[Full error log](https://gist.github.com/iksi/cfac0df6c3fe64f5ad820b4a5906f5d6)

**Comment by iksi** [comment]
Closing this issue as this was caused by running the emulator without the `--headless` flag.
